apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: backend-app
        image: "{{ .Values.image.repository }}/{{ .Values.image.tag }}"
        env:
          - name: SPRING_DB_HOST
            value: "{{ .Values.database.SPRING_DB_HOST }}"
          - name: SPRING_DB_PORT
            value: "{{ .Values.database.SPRING_DB_PORT }}"
          - name: SPRING_DB_NAME
            value: "{{ .Values.database.SPRING_DB_NAME }}"
          - name: SPRING_DB_USER
            value: "{{ .Values.database.SPRING_DB_USER }}"
          - name: SPRING_DB_PASSWORD
            value: "{{ .Values.database.SPRING_DB_PASSWORD }}"
        ports:
          - containerPort: 8080  # Puerto que escucha tu backend
      imagePullSecrets:
        - name: "{{ .Values.image.pullSecret }}"
